export const nav: [string, string][] = [["/how-it-works","How it works"],["/argument-lab","Lab"],["/analysis","Analysis"],["/library","Library"],["/methodology","Method"],["/pricing","Pricing"]];
export const attacks: [string, string][] = [["Logic","Your conclusion depends on an assumption the opposing party can directly challenge."],["Facts","The argument assumes X without establishing the evidentiary basis for X."],["Authority","The cited precedent may be distinguishable on the facts."],["Statute","A statutory provision may limit the clause you rely on."],["Procedure","The relief sought may be time-barred or sought in the wrong forum."],["Evidence","The key document may be unproven or inadmissible as pleaded."],["Jurisdiction","The court may lack territorial or subject-matter competence."],["Policy","Your reading may defeat the very purpose of the rule."]];
export const stagesWords = [{w:"Claim",t:"The defendant’s failure to disclose the defect is a material breach."},{w:"Assumption",t:"Assumes the defendant knew of the defect when the contract was signed."},{w:"Vulnerability",t:"Nothing yet shows what the defendant actually knew."},{w:"Counter",t:"Opposition: the buyer inspected and accepted the goods."},{w:"Stronger argument",t:"Exclusive knowledge plus a pre-contract inspection record establishes breach."}];
export const stages: [string, string][] = [["Claim","Isolate exactly what the court is asked to decide."],["Assumptions","Surface every premise the conclusion silently needs."],["Authorities","Test whether each case truly supports the proposition."],["Facts","Separate what is pleaded, proven, and merely hoped."],["Counterarguments","Draft the opposition’s strongest lines, not its weakest."],["Judicial questions","Anticipate what the bench will ask first."],["Weaknesses","Rank vulnerabilities by the damage they do."],["Rebuilt argument","Redraft so every weak point has an answer."]];
export const fight: [string, string][] = [["Clause 14 excludes consequential damages and the loss claimed is consequential.","Clause 14 does not reach losses flowing directly from the breach."],["Commercial parties of equal power allocated the risk.","Exclusions are read narrowly against the party relying on them."],["Courts uphold clear exclusion clauses.","The clause never defines “consequential”, so it is not clear."],["No wilful default is pleaded.","Concealment of the defect supports an inference of wilful default."]];
export const library = [{t:"Exclusion of consequential loss",j:"India",a:"Contract",s:54,st:"Strengthened",d:"12 Sep"},{t:"Limitation and acknowledgment",j:"India",a:"Contract",s:61,st:"Open",d:"03 Sep"},{t:"Anti-suit injunction forum",j:"Singapore",a:"Arbitration",s:48,st:"Open",d:"28 Aug"},{t:"Duty of care, pure economic loss",j:"England & Wales",a:"Tort",s:77,st:"Strengthened",d:"19 Aug"},{t:"Specific performance of land sale",j:"India",a:"Contract",s:69,st:"Archived",d:"02 Aug"},{t:"Interim relief under s.9",j:"India",a:"Arbitration",s:58,st:"Open",d:"30 Jul"}];
export const tiers = [{n:"Individual",p:"$29",u:"/ month",f:["50 stress tests","Personal library","Export to Word"]},{n:"Pro",p:"$79",u:"/ month",f:["Unlimited tests","Fight Both Sides","Authority checks"]},{n:"Firm",p:"Custom",u:"",f:["Shared library","SSO","Private deployment"]}];
export const method: [string, string][] = [["Understand","Reconstruct the claim and its premises in structured form."],["Challenge","Question every premise the conclusion rests on."],["Contradict","Find statutes, facts or authority that cut against you."],["Distinguish","Separate your cases from the ones that help the other side."],["Attack","Mount the opposition’s strongest case end to end."],["Rebuild","Redraft the argument around what survived."],["Strengthen","Re-test the new version until weak points are answered."]];
export const analysis = {score:72,label:"Moderately resilient",stats:{critical:3,counters:8,questions:5,gaps:2},
vulns:[{title:"Scope of the exclusion clause",sev:"HIGH",why:"The clause may not cover losses outside its contractual definition of consequential damages.",opp:"Loss of profit is a direct loss under the contract’s own wording.",pos:"You assume the loss is consequential without defining it.",fix:"Quote the definition clause and tie each head of loss to it.",q:"Where does the contract define “consequential”?"},
{title:"Contra proferentem",sev:"MEDIUM",why:"The clause may be read narrowly against the party who drafted it.",opp:"Ambiguity should be resolved in the claimant’s favour.",pos:"You treat the clause as unambiguous.",fix:"Show the clause was negotiated, not imposed.",q:"Who drafted clause 14?"},
{title:"Statutory framework",sev:"HIGH",why:"Enforceability is assumed without addressing the statutory background.",opp:"Statute limits contracting out of liability for wilful default.",pos:"No statute is engaged in your draft.",fix:"Add a paragraph on enforceability and the relevant provisions.",q:"Does any statute restrict this exclusion?"}],
counters:["The loss is direct, not consequential.","The clause is ambiguous and must be read against the drafter.","Wilful default sits outside the exclusion.","The defendant’s own conduct bars reliance on the clause."],
questions:["Who drafted this clause?","Is “consequential” defined anywhere?","What did the defendant know, and when?","Which authority binds this court on exclusions?"],
gaps:[{t:"Lead authority is distinguishable",d:"Facts differ on notice and bargaining power."},{t:"No authority on wilful default",d:"Add binding authority or concede the point."}],
rebuilt:"Clause 14 excludes consequential loss as defined in clause 1.3. The losses claimed fall within that definition, the clause was negotiated between commercial parties, and no statutory provision restricts its operation on these facts."};
export type Analysis = typeof analysis;
